[project]
name = "crane-feedstock"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ben Moss <bmoss40@bloomberg.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
rattler-build = ">=0.16.2,<0.17"
